<?php
$name = $argv[1];
include('vars.php');
echo "<domain type='kvm'>\n";
echo "  <name>$name</name>\n";
echo "  <memory unit='KiB'>1048576</memory>\n";
echo "  <currentMemory unit='KiB'>1048576</currentMemory>\n";
echo "  <vcpu placement='static'>2</vcpu>\n";
echo "  <resource>\n";
echo "    <partition>/machine</partition>\n";
echo "  </resource>\n";
echo "  <os>\n";
echo "    <type arch='x86_64' machine='pc-i440fx-xenial'>hvm</type>\n";
echo "    <boot dev='hd'/>\n";
echo "  </os>\n";
echo "  <features>\n";
echo "    <acpi/>\n";
echo "    <apic/>\n";
echo "  </features>\n";
echo "  <cpu mode='custom' match='exact'>\n";
echo "    <model fallback='allow'>Opteron_G5</model>\n";
echo "  </cpu>\n";
echo "  <clock offset='utc'>\n";
echo "    <timer name='rtc' tickpolicy='catchup'/>\n";
echo "    <timer name='pit' tickpolicy='delay'/>\n";
echo "    <timer name='hpet' present='no'/>\n";
echo "  </clock>\n";
echo "  <on_poweroff>destroy</on_poweroff>\n";
echo "  <on_reboot>restart</on_reboot>\n";
echo "  <on_crash>restart</on_crash>\n";
echo "  <pm>\n";
echo "    <suspend-to-mem enabled='no'/>\n";
echo "    <suspend-to-disk enabled='no'/>\n";
echo "  </pm>\n";
echo "  <devices>\n";
echo "    <emulator>/usr/bin/kvm-spice</emulator>\n";
echo "    <disk type='file' device='disk'>\n";
echo "      <driver name='qemu' type='qcow2'/>\n";
echo "      <source file='$dir$name.img'/>\n";
echo "      <backingStore/>\n";
echo "      <target dev='vda' bus='virtio'/>\n";
echo "      <alias name='virtio-disk0'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>\n";
echo "    </disk>\n";
echo "    <disk type='file' device='cdrom'>\n";
echo "      <driver name='qemu' type='raw'/>\n";
echo "      <backingStore/>\n";
echo "      <target dev='hda' bus='ide'/>\n";
echo "      <readonly/>\n";
echo "      <alias name='ide0-0-0'/>\n";
echo "      <address type='drive' controller='0' bus='0' target='0' unit='0'/>\n";
echo "    </disk>\n";
echo "    <controller type='usb' index='0' model='ich9-ehci1'>\n";
echo "      <alias name='usb'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x7'/>\n";
echo "    </controller>\n";
echo "    <controller type='usb' index='0' model='ich9-uhci1'>\n";
echo "      <alias name='usb'/>\n";
echo "      <master startport='0'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0' multifunction='on'/>\n";
echo "    </controller>\n";
echo "    <controller type='usb' index='0' model='ich9-uhci2'>\n";
echo "      <alias name='usb'/>\n";
echo "      <master startport='2'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x1'/>\n";
echo "    </controller>\n";
echo "    <controller type='usb' index='0' model='ich9-uhci3'>\n";
echo "      <alias name='usb'/>\n";
echo "      <master startport='4'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x2'/>\n";
echo "    </controller>\n";
echo "    <controller type='pci' index='0' model='pci-root'>\n";
echo "      <alias name='pci.0'/>\n";
echo "    </controller>\n";
echo "    <controller type='ide' index='0'>\n";
echo "      <alias name='ide'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>\n";
echo "    </controller>\n";
echo "    <controller type='virtio-serial' index='0'>\n";
echo "      <alias name='virtio-serial0'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>\n";
echo "    </controller>\n";
echo "    <interface type='bridge'>\n";
echo "      <mac address='52:54:00:cc:a9:0d'/>\n";
echo "      <source bridge='virbr0'/>\n";
echo "      <target dev='vnet1'/>\n";
echo "      <model type='virtio'/>\n";
echo "      <alias name='net0'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>\n";
echo "    </interface>\n";
echo "    <serial type='pty'>\n";
echo "      <source path='/dev/pts/3'/>\n";
echo "      <target port='0'/>\n";
echo "      <alias name='serial0'/>\n";
echo "    </serial>\n";
echo "    <console type='pty' tty='/dev/pts/3'>\n";
echo "      <source path='/dev/pts/3'/>\n";
echo "      <target type='serial' port='0'/>\n";
echo "      <alias name='serial0'/>\n";
echo "    </console>\n";
echo "    <channel type='unix'>\n";
echo "      <source mode='bind' path='/var/lib/libvirt/qemu/channel/target/domain-user2/org.qemu.guest_agent.0'/>\n";
echo "      <target type='virtio' name='org.qemu.guest_agent.0' state='connected'/>\n";
echo "      <alias name='channel0'/>\n";
echo "      <address type='virtio-serial' controller='0' bus='0' port='1'/>\n";
echo "    </channel>\n";
echo "    <input type='tablet' bus='usb'>\n";
echo "      <alias name='input0'/>\n";
echo "    </input>\n";
echo "    <input type='mouse' bus='ps2'/>\n";
echo "    <input type='keyboard' bus='ps2'/>\n";
echo "    <graphics type='vnc' port='-1' autoport='yes' listen='10.0.0.24'>\n";
echo "      <listen type='address' address='10.0.0.24'/>\n";
echo "    </graphics>\n";
echo "    <video>\n";
echo "      <model type='cirrus' vram='16384' heads='1'/>\n";
echo "      <alias name='video0'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>\n";
echo "    </video>\n";
echo "    <memballoon model='virtio'>\n";
echo "      <alias name='balloon0'/>\n";
echo "      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>\n";
echo "    </memballoon>\n";
echo "  </devices>\n";
echo "  <seclabel type='dynamic' model='apparmor' relabel='yes'>\n";
echo "    <label>libvirt-07650553-2bd6-4b22-a017-2beb9d0b356e</label>\n";
echo "    <imagelabel>libvirt-07650553-2bd6-4b22-a017-2beb9d0b356e</imagelabel>\n";
echo "  </seclabel>\n";
echo "</domain>\n";
?>
